### ISSUE TITLE
Access denied after change root password

### ISSUE THREAD

**Issue by zm1994** [memsql/memsql-docker-quickstart#19]
There is problem with access to nodes after changing root password and removing container.
Steps to reproduce:
1. Create container with memsql and mount '/memsql' directory to host;
2 Go to the running container with docker exec;
3 Change root password with command
memsql-ops memsql-list -q | xargs -n 1 memsql-ops memsql-update-root-password --no-confirmation -p "your new password";
4 Check connection success with new password;
5 Remove container and recreate new with previously mounted folder;
6 Run container.
Actual state: "ERROR: ProcessHandshakeResponsePacket() failed. Sending back 1045: Access denied for user 'root'@'localhost'"

**Comment by carlsverre** [comment]
It sounds like the bug is the host parameter of the mysql connection command.  You must specify the ip address of the container or `127.0.0.1` explicitely.  If you specify `localhost` or don't specify `--host` at all then the `mysql` client will attempt to connect via a unix domain socket at a default location of `/var/run/mysql.sock` (might be wrong on the default path).

Make sure you are trying to connect to the container with something like `mysql -u root -h 127.0.0.1 -p`.  This will prompt for the password that you set.

**Comment by zm1994** [comment]
The problem is that recreated container failed to start with error: "Starting cluster
MemSQL node 0751A1F427CB46B6CC8EC3EE0C542FF57FB5EEA0 failed to start: Failed to connect to MemSQL node 0751A1F427CB46B6CC8EC3EE0C542FF57FB5EEA0: ProcessHandshakeResponsePacket() failed. Sending back 1045: Access denied for user 'root'@'localhost' (using password: NO)".
I found one solution: mounting folder /memsql-ops which contains the information about nodes, but i don't know if this is good idea, or not.

**Comment by carlsverre** [comment]
Ah, I understand the problem.  It was unclear since your original ticket made it sound like you were getting the ACCESS DENIED error from the mysql client rather than from Ops.  Yes, the problem is that the memsql-ops state is being mutated, and the new container doesn't have the updated state.  To solve this you can mount the /memsql-ops directory into a volume which will save all of the state.

Also take a look at the minimal version of the image which doesn't include Ops.  It's designed for scripting/testing workloads which may be closer to what you are looking for: https://github.com/memsql/memsql-docker-quickstart/tree/minimal
